---
- name: Install java and net-tools
  hosts: 13.38.0.160
  become: yes
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install Java 8
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools
- name: Download and unpack Nexus installer
  hosts: 13.38.0.160
  become: yes
  tasks:
    - name: Download Nexus
      get_url: 
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
- name: Untar nexus installer
  unarchive: 
    src: /opt/
    dest: