---
- name: Configure nginx web server
  hosts: webserver
  tasks:
  - name: install nginx server
    apt: 
      name: nginx
      state: latest
  - name: start nginx
    service:
      name: nginx
      state: started